services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    restart: unless-stopped
    ports:
      - "127.0.0.1:8003:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://broadway:${DB_PASSWORD}@postgres-shared:5432/broadway
    volumes:
      - ./seeds:/broadway/seeds
    networks:
      - db_network

networks:
  db_network:
    external: true
